import Head from 'next/head'
import { useEffect, useState } from 'react';
import dynamic from 'next/dynamic';

const MobileView = dynamic( () => import( '@/views/MobileView' ), {
  ssr: false
} );
const DesktopView = dynamic( () => import( '@/views/DesktopView' ), {
  ssr: false
} );

export default function Home ()
{
  const [screenSize, setScreenSize] = useState( {
    width: typeof window !== 'undefined' ? window.innerWidth : 0,
    height: typeof window !== 'undefined' ? window.innerHeight : 0
  } );

  const MOBILE = 600

  useEffect( () =>
  {
    const handleResize = (): void =>
    {
      setScreenSize( {
        width: window.innerWidth,
        height: window.innerHeight
      } );
    };

    window.addEventListener( 'resize', handleResize );

    return () =>
    {
      window.removeEventListener( 'resize', handleResize );
    };
  }, [] );

  return (
    <>
      <Head>
        <title>E-Resume</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* {screenSize.width > MOBILE ? <><DesktopView /></> : <><MobileView /></>} */}
        <DesktopView />
      </main>
    </>
  )
}
